[package]
name = "compusch"
version = "0.1.0"
authors = ["Denis"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.3.0"
regex = "1.5"
